services:
  # --- DATABASE (PostgreSQL) ---
  postgres_db:
    image: postgres:15-alpine
    container_name: advisor_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - advisor_net

  # --- MESSAGE BROKER (Redis) ---
  redis_broker:
    image: redis:7-alpine
    container_name: advisor_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - advisor_net

  # --- WEBHOOK MANAGER ---
  webhook-manager:
    build: ./webhook-manager
    container_name: webhook_manager
    restart: on-failure
    ports:
      - "3000:3000" #Webhooks incoming from gh
    depends_on:
      - redis_broker
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:6379
      - REDIS_QUEUE_NAME=${REDIS_QUEUE}
      - PORT=3000
    networks:
      - advisor_net

  # --- AI AGENT (MOCK) ---
  agent:
    build: ./agent
    container_name: agent
    restart: on-failure
    depends_on:
      - redis_broker
      - postgres_db
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:6379
      - REDIS_QUEUE_NAME=${REDIS_QUEUE}
      - REDIS_CHANNEL_NAME=${REDIS_CHANNEL}
      # connection string: postgresql://USER:PASSWORD@HOSTNAME:PORT/DB_NAME
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}
      - PYTHONUNBUFFERED=1
    networks:
      - advisor_net

  # --- BACKEND CLIENT ---
  backend-client:
    build: ./backend-client
    container_name: backend_client
    restart: on-failure
    ports:
      - "3001:3001" # Port for React to talk to
    depends_on:
      - redis_broker
      - postgres_db
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:6379
      - REDIS_CHANNEL_NAME=${REDIS_CHANNEL}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}
      - PORT=3001
    networks:
      - advisor_net
      
# --- FRONTEND CLIENT ---
  frontend-client:
    build: ./frontend-client
    container_name: frontend_client
    restart: on-failure
    ports:
      - "5173:5173"
    depends_on:
      - backend-client
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_USE_MOCK_DATA=false # Toggle this to use mock data
    networks:
      - advisor_net
    
volumes:
  postgres_data:

networks:
  advisor_net:
    driver: bridge