services:
  # --- DATABASE (PostgreSQL) ---
  postgres_db:
    image: postgres:15-alpine
    container_name: advisor_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - advisor_net

  # --- MESSAGE BROKER (Redis) ---
  redis_broker:
    image: redis:7-alpine
    container_name: advisor_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - advisor_net

  # --- WEBHOOK MANAGER ---
  webhook-manager:
    build: ./webhook-manager
    container_name: webhook_manager
    restart: on-failure
    ports:
      - "3000:3000" #Webhooks incoming from gh
    depends_on:
      - redis_broker
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:6379
      - REDIS_QUEUE_NAME=${REDIS_QUEUE}
      - PORT=3000
    networks:
      - advisor_net

  # --- AI AGENT (MOCK) ---
  agent:
    build: ./agent
    container_name: agent
    restart: on-failure
    depends_on:
      - redis_broker
      - postgres_db
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:6379
      - REDIS_QUEUE_NAME=${REDIS_QUEUE}
      # connection string: postgresql://USER:PASSWORD@HOSTNAME:PORT/DB_NAME
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}
      - PYTHONUNBUFFERED=1
    networks:
      - advisor_net
      
volumes:
  postgres_data:

networks:
  advisor_net:
    driver: bridge